apiVersion: rabbitmq.improvado.io/v1
kind: Rabbitmq
metadata:
  name: imp20rabbit
spec:
  replicas: 2
  image:
    name: rabbitmq
    tag: 3-alpine
  rabbitmqUsername: rabbituser
  volumeSize: 1Gi
  policies:
    - name: ha-three
      pattern: ".*"
      definition: 
        ha-mode: exactly
        ha-params: "3"
        ha-sync-mode: automatic
      priority: 1
      applyto: all
