---
apiVersion: rabbitmq.improvado.io/v1
kind: Rabbitmq
metadata:
  name: imp20rabbit
spec:
  replicas: 2
  image:
    name: rabbitmq
    tag: 3-alpine
  default_username: "rabbit"
  default_vhost: "rabbit"
  default_password: "rabbit"
  memory_high_watermark: 256M
  k8s_host: "kubernetes.default.svc.cluster.imp"
  k8s_addrtype: hostname
  cluster_node_cleanup_interval: 10
  volume_size: 1Gi
  policies:
    - name: ha-three
      pattern: ".*"
      definition: 
        ha-mode: exactly
        ha-params: "3"
        ha-sync-mode: automatic
      priority: 1
      applyto: all
